apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fullstack-rag-fastapi-service
  annotations:
    # Adding a unique annotation to force a redeployment
    updated-at: "2024-08-08T14:40:49"
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/fullstack-rag/fullstack-rag-fastapi/fullstack-rag-fastapi
          env:
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ANTHROPIC_API_KEY
                  key: latest
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: POSTGRES_URL
                  key: latest
            - name: AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: AUTH_SECRET_KEY
                  key: latest
            - name: AUTH_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: AUTH_ALGORITHM
                  key: latest
            - name: LANGCHAIN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: LANGCHAIN_ENDPOINT
                  key: latest
            - name: LANGCHAIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: LANGCHAIN_API_KEY
                  key: latest
            - name: SERPER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: SERPER_API_KEY
                  key: latest
          ports:
            - containerPort: 4000